apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
data:
  KAFKA_BOOTSTRAP_SERVER: "kafka-broker-service:9092"
  KAFKA_TOPIC: "posts"
  KAFKA_GROUP_ID: "post_consumers"