apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /airflow/dags  # Define the host path where the directory is available
