apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-service
spec:
  selector:
    app: kafka-broker  # Aligné avec le deployment Kafka
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
  type: ClusterIP
