apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-pusher-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-pusher-kafka
  template:
    metadata:
      labels:
        app: post-pusher-kafka
    spec:
      containers:
      - name: post-pusher-kafka
        image: 2024_kubernetes_post_pusher
        imagePullPolicy: Never
        command: ["python", "main.py", "--multiple", "--kafka_host=kafka-broker-service:9092"]